# do this when a new issue is created
on:
  issues:
    types: [opened]
  workflow_dispatch:
    inputs:
      meditation:
        description: 'Generate a meditation'
        required: true
        default: 'true'

jobs:
  generate-meditation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/CommitCalm/requirements.txt
    # TODO: Replace with OIDC
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.COMMITCALM_AZURE_CREDENTIALS }}
    - name: Run the meditation script
      run: python src/CommitCalm/basic_promptflow.py --topic ${{ github.event.issue.body }}" > meditation.txt
    - name: Publish the meditation
      uses: actions/upload-artifact@v2
      with:
        name: meditation
        path: meditation.txt
