# do this when a new issue is created
on:
  issues:
    types: [opened]

jobs:
    hello-world:
        runs-on: ubuntu-latest
        steps:
            - name: Hello world action step
              id: hello
              run: echo "Hello world!"
            - name: Read the issue
              id: read-issue
              run: echo "The issue is ${{ github.event.issue.title }}"
            - name: "Body of the issue"
              id: body
              run: echo "The body of the issue is ${{ github.event.issue.body }}"
            - name: View the github context
              run: echo "$GITHUB_CONTEXT"
              env:
                GITHUB_CONTEXT: ${{ toJson(github) }}
